name: scbm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pytorch-cuda
  - cuda-toolkit=12.1
  - pytorch
  - torchvision
  - wandb
  - scikit-learn
  - tqdm
  - torchmetrics=0.11.4
  - matplotlib
  - conda-forge::hydra-core
  - plotly
  - anaconda::seaborn
  - transformers=4.37.2
  - pip
  - pip:
    - pytorch-minimize

